### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Filippo780** [galehouse5/skribbl-io-autodraw#20] opened 2020-04-21 18:25 UTC
IT DOESN'T WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by samueld08** [comment] 2020-04-23 12:53
ikr

**Comment by SungMatt** [comment] 2020-04-25 16:55
Have you tried [this](https://github.com/galehouse5/skribbl-io-autodraw/issues/17#issuecomment-605659328) fix?

Also, kind reminder: It doesn't quite help to just put "it doesn't work" in a GitHub repo. Try adding some basic information like the OS you're working with, and the browser you're working with. Helps a lot when it comes to resolving issues.

**Comment by galehouse5** [comment] 2020-05-08 03:49
Duplicate of #17.

**Closed by galehouse5** 2020-05-08 03:49 UTC
