### ISSUE TITLE
just remove the looping over diameters and only using diameter 4

### ISSUE THREAD

**Issue by gellyfisher** [galehouse5/skribbl-io-autodraw#8] opened 2019-02-12 17:30 UTC
If only diameter 4 is used then there is enough time to draw and the picture looks much much better

**Comment by GlitchMasta47** [comment] 2019-06-19 22:19
tl;dr doing this will take longer to draw images than the time allowed by the game

> The limiting factor is the rate skribbl.io servers process line draw commands. It's somewhere between 5,000 and 10,000 per minute. The image above contains 30,000 pixels so the naive method of using one line draw command per pixel would take 3 to 6 minutes. https://github.com/galehouse5/skribbl-io-autodraw/issues/6#issuecomment-457998328

Merge this issue with #6 I guess

**Comment by galehouse5** [comment] 2019-06-23 22:59
Duplicate of #6.

**Closed by galehouse5** 2019-06-23 22:59 UTC
Labels: duplicate
